name: Frontend Tests

on:
  push:
    branches:
      - develop
      - master
  pull_request:

env:
  NODE_OPTIONS: --max-old-space-size=5500

jobs:
  test_suite:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - uses: actions/checkout@v2

    - name: Get npm cache directory
      id: npm-cache-dir
      shell: bash
      run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}

    - uses: actions/cache@v3
      id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
      with:
        path: ${{ steps.npm-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install Dependencies
      run: npm install

    - name: Run Tests
      uses: coactions/setup-xvfb@v1
      with:
        run: npm run test
